// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("messages")]
	public class Message
	{
		[Column("id"                  , SkipOnInsert = true, IsPrimaryKey = true )] public Guid           Id                 { get; set; } // uuid
		[Column("ephemeral_public_key", CanBeNull    = false)] public byte[]         EphemeralPublicKey { get; set; } = null!; // bytea
		[Column("nonce"               , CanBeNull    = false)] public byte[]         Nonce              { get; set; } = null!; // bytea
		[Column("ciphertext"          , CanBeNull    = false)] public byte[]         Ciphertext         { get; set; } = null!; // bytea
		[Column("tag"                 , CanBeNull    = false)] public byte[]         Tag                { get; set; } = null!; // bytea
		[Column("sender_id"                                 )] public Guid           SenderId           { get; set; } // uuid
		[Column("timestamp"           , SkipOnInsert = true )] public DateTimeOffset Timestamp          { get; set; } // timestamp (6) with time zone

		#region Associations
		/// <summary>
		/// messages_sender_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(SenderId), OtherKey = nameof(User.Id))]
		public User Sender { get; set; } = null!;

		/// <summary>
		/// recipient_entries_message_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(RecipientEntry.MessageId))]
		public IEnumerable<RecipientEntry> RecipientEntries { get; set; } = null!;
		#endregion
	}
}
