// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using LinqToDB.Async;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class OnChatDb : DataConnection
	{
		public OnChatDb()
		{
			InitDataContext();
		}

		public OnChatDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public OnChatDb(DataOptions<OnChatDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Message> Messages => this.GetTable<Message>();
		public ITable<User>    Users    => this.GetTable<User>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Message? Find(this ITable<Message> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Message?> FindAsync(this ITable<Message> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}

		public static User? Find(this ITable<User> table, Guid id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<User?> FindAsync(this ITable<User> table, Guid id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
