// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("recipient_entries")]
	public class RecipientEntry
	{
		[Column("id"          , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long   Id          { get; set; } // bigint
		[Column("message_id"                                                                                     )] public Guid   MessageId   { get; set; } // uuid
		[Column("recipient_id"                                                                                   )] public Guid   RecipientId { get; set; } // uuid
		[Column("nonce"       , CanBeNull    = false                                                             )] public byte[] Nonce       { get; set; } = null!; // bytea
		[Column("ciphertext"  , CanBeNull    = false                                                             )] public byte[] Ciphertext  { get; set; } = null!; // bytea
		[Column("tag"         , CanBeNull    = false                                                             )] public byte[] Tag         { get; set; } = null!; // bytea

		#region Associations
		/// <summary>
		/// recipient_entries_message_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(MessageId), OtherKey = nameof(DataModel.Message.Id))]
		public Message Message { get; set; } = null!;

		/// <summary>
		/// recipient_entries_recipient_id_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(RecipientId), OtherKey = nameof(User.Id))]
		public User Recipient { get; set; } = null!;
		#endregion
	}
}
