// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("users")]
	public class User
	{
		[Column("id"           , SkipOnInsert = true,  IsPrimaryKey = true)] public Guid    Id           { get; set; } // uuid
		[Column("mail"                              )] public string Mail         { get; set; } = null!; // character varying(255)
		[Column("username"                          )] public string Username     { get; set; } = null!; // character varying(50)
		[Column("password_hash"                     )] public string PasswordHash { get; set; } = null!;// character varying(512)
		[Column("age"                               )] public short  Age          { get; set; } // smallint
		[Column("public_key"                        )] public byte[]? PublicKey    { get; set; } // bytea

		#region Associations
		/// <summary>
		/// messages_sender_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Message.SenderId))]
		public IEnumerable<Message> Messages { get; set; } = null!;

		/// <summary>
		/// recipient_entries_recipient_id_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(RecipientEntry.RecipientId))]
		public IEnumerable<RecipientEntry> RecipientEntries { get; set; } = null!;
		#endregion
	}
}
